[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt"
]
